# -*- coding: utf-8 -*-
"""Flask_demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lfJD2MuWLM3tUDgWEPLWJtQ0mHB8iWfg
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install flask
# !pip install flask_restful
# 
# !pip install spacytextblob
# !python -m textblob.download_corpora
# !python -m spacy download en_core_web_sm

from flask import Flask, request
from flask_restful import Resource, Api, reqparse

import spacy
from spacytextblob.spacytextblob import SpacyTextBlob

nlp = spacy.load('en_core_web_sm')
nlp.add_pipe('spacytextblob')

app = Flask(__name__)
api = Api(app)

parser = reqparse.RequestParser()  # used to parse incoming requests
parser.add_argument('review', required=True,
                    help='Por favor escribe algo. / Please write something.')

class PredictSentiment(Resource):
    def post(self):
        args = parser.parse_args()
        review = args['review']
        doc = nlp(review)
        score = doc._.polarity
        return {'score': score}

api.add_resource(PredictSentiment, '/predict')

if __name__ == '__main__':
    app.run()